### PR TITLE
Some minor reorganization

### PR DESCRIPTION
**Pull request by lars-sh**
* Reorganize assembly
* Remove unused restarter class
* Clean up and add missing README.md files
* Simplify custom lombok.config

### CODE REVIEW

**Comment by noxone** [comment]
The VisualStudio Code Markdown linter requests a blank line after each header. Would it be possible to auto format Markdown files, too?

**Comment by lars-sh** [comment]
Oh, didn't know that and will update this request tomorrow.

As I'm using just plain Notepad++ or Eclipse die markdown I guess we won't have a good base for automated formatting.

**Comment by lars-sh** [comment]
OK, I finally tried to reproduce your problem with the VS Code MarkDown linter. Which VS Code plugin do you use and when does it show up the warnings?

**Comment by noxone** [comment]
https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
Currently nearly every markdown file (including our readme) shows up warnings.

**Comment by lars-sh** [comment]
OK, installed it. Most rules are OK for me, but MD010 is really not. How to go on with that one?

**Pull request closed without merging**
