### PR TITLE
Welcome page

### PR DESCRIPTION
**Pull request by noxone**
THis Pull request adds the names of the dashboard owners to the welcome page.

### CODE REVIEW

**Comment by lars-sh** [comment]
@noxone what about this?

**Comment by noxone** [comment]
ok,@lars-sh, I think this one is ready for merge. Please add a review.

**Comment by lars-sh** [comment]
See above review: Is it possible to merge getOwnerName and getOwnerMail into getAnyOwnerPrincipal?

The new stuff is OK.

**Comment by noxone** [comment]
Sorry, I don't understand your request. Do you want to merge the `getOwnerMail` and `getOwnerName` functions that are handed over to the template engine into one interface?

**Pull request merged**
