### PR TITLE
Rebuild Wro4j model

### PR DESCRIPTION
**Pull request by noxone**
OK, in this branch I reconfigured the wro4j servlet.
It will not be configured using the `wro.xml` but the configuration is now also part of the `config.json`. The discovery and the URI creation will be done by oversigt code and wro4j will only be used to actually load the resource.

### CODE REVIEW

**Comment by noxone** [comment]
Looks liek there's a problem with the pom...

**Comment by noxone** [comment]
OK, now the project isn't building because of the `-html5` parameter.
I won't fix that. Either we need to ignore javadoc-warnings when using JDK 10, or Travis needs to use JDK10 for compiling.

**Comment by lars-sh** [comment]
Thanks for fixing the missing versions - I just removed them from the parent snapshot without updating oversigt. There should have be a release version, yet to avoid such problems...

Regarding the JavaDoc stuff I'd suggest reverting to JDK8 as that's what overigt code is build for and setting the Maven property "maven.javadoc.failOnWarnings" to "false".

**Comment by lars-sh** [comment]
OK, I just thought about a better solution for this. Please try the following. In case it works, I'd like to add it to the parent POM so every project takes profit thereof.

Pleae revert Travis CI and your changes to the "additionalOptions" property. Finally copy and paste the following into the root of one of the POMs.

In case I didn't do a mistake, it should add the additional option "-html4" whenever a JDK 9 and upper is used. I'm not that sure about the JDK naming convention.

- It might need to be changed to "(1.9,)" instead.
- Does "-html4" work? Even though it's not my favorite choice, it keeps the output similar to older JDKs.

```
	<profiles>
		<profile>
			<activation>
				<jdk>(9,)</jdk>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
						<configuration>
							<additionalOptions>-html4</additionalOptions>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
```

**Comment by noxone** [comment]
Alright... now only spotbugs is intercepting.
Actually this is a method I just copied from OpenJDK - which is very complex, just as Spotbugs is complayning -.-

**Comment by lars-sh** [comment]
Fine, we're getting closer 😏 .

Then just add `@SuppressFBWarnings(value = "CC_CYCLOMATIC_COMPLEXITY", justification = "copied from OpenJDK as is")`

**Pull request merged**
